# Generated by Django 5.0.4 on 2024-04-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='titile',
            new_name='title',
        ),
    ]
